Item(by='oefrha', descendants=None, kids=[24829037], score=None, time=1603129580, title=None, item_type='comment', url=None, parent=24827844, text='Not sure what you mean by shaky, fail2ban has been working under Python 3 for quite a while. (See for instance fail2ban on Ubuntu 16.04 depending on python3[0].) People definitely would have noticed.<p>I saw your issue[1] on GitHub, and that&#x27;s just a misunderstanding of how fail2ban was ported to Python 3. fail2ban uses the use_2to3 feature of setuptools.setup to do automatic translation upon installation.[2] While I do wish the code runs under Python 3 as is, what users actually run is totally working code.<p>[0] <a href="https:&#x2F;&#x2F;packages.ubuntu.com&#x2F;xenial&#x2F;amd64&#x2F;fail2ban" rel="nofollow">https:&#x2F;&#x2F;packages.ubuntu.com&#x2F;xenial&#x2F;amd64&#x2F;fail2ban</a><p>[1] <a href="https:&#x2F;&#x2F;github.com&#x2F;fail2ban&#x2F;fail2ban&#x2F;issues&#x2F;2853" rel="nofollow">https:&#x2F;&#x2F;github.com&#x2F;fail2ban&#x2F;fail2ban&#x2F;issues&#x2F;2853</a><p>[2] <a href="https:&#x2F;&#x2F;github.com&#x2F;fail2ban&#x2F;fail2ban&#x2F;blob&#x2F;960e30cfcdae7e2c81f74046efdbff1606f9774e&#x2F;setup.py#L178-L182" rel="nofollow">https:&#x2F;&#x2F;github.com&#x2F;fail2ban&#x2F;fail2ban&#x2F;blob&#x2F;960e30cfcdae7e2c81...</a>')