Item(by='FridgeSeal', descendants=None, kids=None, score=None, time=1606806069, title=None, item_type='comment', url=None, parent=25254137, text='After learning how Rust&#x2F;Haskell do error handling and how to use it, going back to Python&#x27;s exception causes almost physical pain.<p>There is no distinction drawn between &quot;small error&quot; and &quot;catastrophic failure&quot;, anywhere, at anytime, some piece of underlying code may throw nearly nearly any exception up at you by surprise which is a fun adventure in &quot;what will fail next when I shift my attention away slightly&quot;. So few libraries properly utilise context: &quot;ValueError on line 1:44&quot; in whatever large file you&#x27;re reading through (looking at you Pandas), doesn&#x27;t tell me what the data was, nor what it was expecting, or the real line&#x2F;position in the file or give you any way of recovering and resuming.')