Item(by='dancrystalbeach', descendants=3, kids=[25660620, 25659645, 25659406], score=4, time=1609951739, title='The Utter Failure of Async in Python', item_type='story', url='https://www.confessionsofadataguy.com/the-utter-failure-of-async-in-python/', parent=None, text=None)