Item(by='inbx0', descendants=None, kids=[25775589], score=None, time=1610616716, title=None, item_type='comment', url=None, parent=25772282, text='Your fetch examples don&#x27;t reject the promise if the server responds with error status code, like 404, which is probably not what you&#x27;d want. You&#x27;d need to handle that separately with something like<p><pre><code>    const resp = await fetch(&#x27;&#x2F;my-url&#x27;)\n    if (!resp.ok) throw new Error(await resp.text())\n    const data = await resp.json()\n</code></pre>\nFrom MDN (<a href="https:&#x2F;&#x2F;developer.mozilla.org&#x2F;en-US&#x2F;docs&#x2F;Web&#x2F;API&#x2F;Fetch_API" rel="nofollow">https:&#x2F;&#x2F;developer.mozilla.org&#x2F;en-US&#x2F;docs&#x2F;Web&#x2F;API&#x2F;Fetch_API</a>):<p>&gt; The Promise returned from fetch() wonâ€™t reject on HTTP error status even if the response is an HTTP 404 or 500. Instead, it will resolve normally (with ok status set to false), and it will only reject on network failure or if anything prevented the request from completing.')