Item(by='computronus', descendants=None, kids=[25991878], score=None, time=1612203098, title=None, item_type='comment', url=None, parent=25991146, text='We (my team) hit this as well with an automated compatibility test running on Ubuntu 16.04. I decided to just change the test to install Python 3.8 from the deadsnakes PPA, and then use get-pip.py to install pip.<p><a href="https:&#x2F;&#x2F;launchpad.net&#x2F;~deadsnakes&#x2F;+archive&#x2F;ubuntu&#x2F;ppa" rel="nofollow">https:&#x2F;&#x2F;launchpad.net&#x2F;~deadsnakes&#x2F;+archive&#x2F;ubuntu&#x2F;ppa</a><p>This does change the test to no longer use Python 3.5, but considering a) we&#x27;d already dropped support for Python 3.5 for the code we were testing, b) Python 3.5 is EOL and c) Ubuntu 16.04 will be soon, it didn&#x27;t seem worth trying to stay on 3.5.')